#!/usr/bin/env bash
for i in {1..100}
do
	mul3=$(( i % 3 ))
	mul5=$(( i % 5 ))
	if [ $mul3 -eq 0 ] && [ $mul5 -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $mul3 -eq 0 ]
	then
		echo "Fizz"
	elif [ $mul5 -eq 0 ]
	then
		echo "Buzz"
	else
		echo $i
	fi
done

