#!/usr/bin/env bash
# Use of if elif and else statements

pos=0
while [ $pos -ne 10 ]
do
	if [ $pos -eq 3 ]
	then
		echo "bad luck"
	elif [ $pos -eq 7 ]
	then
		echo "good luck"
	else	
		echo "Best School"
	fi
	(( "pos = pos + 1" ))
done

