#!/usr/bin/env bash
#displays 4 and then bad luck from China for the 4th loop iteration
#displays 9 and then bad luck from Japan for the 9th loop iteration
#displays 17 and then bad luck from Italy for the 17th loop iteration

number=0
pos=0
while [ $number -ne 20 ]
do
	pos=$(( number + 1 ))
	echo $pos

	case $pos in
	
	4) echo "bad luck from China"
	;;
	9) echo "bad luck from Japan"
	;;
	17) echo "bad luck from Italy"
	;;
	esac
	(( "number = number + 1" ))
done

