#!/usr/bin/env bash
# display time 
hour=0
while [ $hour -ne 25 ]
do
	echo "Hour: $hour"
	minutes=1
	while [ $minutes -ne 60 ]
	do
		echo $minutes
		minutes=$(( minutes + 1 ))
	done
	hour=$(( hour + 1 ))
done

