#!/usr/bin/env bash
# Test school file
file_="school"

if [ -e $file_ ]
then
	echo "school file exists"
	if [ -s $file_ ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f $file_ ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi

